# Generated from kramdown-2.3.0.gem by gem2rpm -*- rpm-spec -*-
%define rbname kramdown
%define version 2.3.0
%define release 1

Summary: kramdown is a fast, pure-Ruby Markdown-superset converter.
Name: rubygem-%{rbname}

Version: %{version}
Release: %{release}
Group: Development/Ruby
License: Distributable
URL: http://kramdown.gettalong.org
Source0: %{rbname}-%{version}.gem
BuildRoot: %{_tmppath}/%{name}-%{version}-root
Requires: ruby >= 2.3
Requires: rubygems >= 2.7.6.2
Requires: rubygem-rexml 
Requires: rubygem-minitest >= 5.0
Requires: rubygem-minitest < 6
Requires: rubygem-rouge 
Requires: rubygem-stringex >= 1.5.1
Requires: rubygem-stringex < 1.6
BuildRequires: ruby >= 2.3
BuildRequires: rubygems >= 2.7.6.2
BuildArch: noarch
Provides: ruby(kramdown) = %{version}

%define gemdir /usr/share/gems
%define gembuilddir %{buildroot}%{gemdir}

%description
kramdown is yet-another-markdown-parser but fast, pure Ruby,
using a strict syntax definition and supporting several common extensions.


%prep
%setup -T -c

%build

%install
%{__rm} -rf %{buildroot}
mkdir -p %{gembuilddir}
gem install --local --user-install --force %{SOURCE0}
mv $(ruby -r rubygems -e 'puts Gem.user_dir')/* %{gembuilddir}
mkdir -p %{buildroot}/%{_bindir}
mv %{gembuilddir}/gems/%{rbname}-%{version}/bin/** %{buildroot}/%{_bindir}

%clean
%{__rm} -rf %{buildroot}

%files
%doc %{gemdir}/doc/%{rbname}-%{version}/
%defattr(-, root, root)
%{_bindir}/kramdown
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/
%{gemdir}/gems/kramdown-2.3.0/


%{gemdir}/cache/kramdown-2.3.0.gem
%{gemdir}/specifications/kramdown-2.3.0.gemspec

%changelog
